### ISSUE TITLE
Invalid query type

### ISSUE THREAD

**Issue by gajus** [tricinel/highlight-words#19]
https://github.com/tricinel/highlight-words/blob/8183ed5b5f004584428cc9281d6e50997b0340b4/src/index.ts#L15

Should also include RegExp

**Comment by gajus** [comment]
Never mind. Just realized that RegExp needs to be provided as a string. Is there a reason for that?

**Comment by tricinel** [comment]
You can still provide it as a RegExp I think, so this will work:

```js
highlightWords({
  text: 'The quick brown fox jumped over the lazy dog',
  query: /(quick|brown|fox)/
})
```

But it will complain that query not a string. I think I couldn't properly type the RegExp because its type is actually an object in JS. You're more than welcome to try though.
