### ISSUE TITLE
Query words with double spaces

### ISSUE THREAD

**Issue by Geksanit** [tricinel/highlight-words#25]
https://codesandbox.io/s/highlight-words-vanilla-forked-qcgv7l?file=/src/index.js
This is an unexpected result.
![image](https://user-images.githubusercontent.com/31949379/194403524-c89637b5-b01c-46f2-830e-7aad076e2e60.png)

**Comment by Geksanit** [comment]
expected result is the same as with one space
![image](https://user-images.githubusercontent.com/31949379/194404175-d9cd8180-9d82-43e2-9617-9379b13ca7a6.png)

**Comment by tricinel** [comment]
Hi @Geksanit! Nice catch! I'm not sure though if it should be the expected result. I think prepping the query should be in the hands of the consumer, otherwise we might end up stripping things we're not supposed to from the query.

You raise a good question though...what should the expected result then be? I'm not sure, so I'll have a think.

**Comment by Geksanit** [comment]
Hi @tricinel Perhaps the query should be an array of string?

**Comment by tricinel** [comment]
Definitely not! I don't see how that would help. I think I have it sorted though.

1. If the query contains more than one space in the middle, we will strip it. So `over the` and `over  the` and `over   the` all are equivalent to searching for `(over|the)`.
2. If the consumer specifically wants the double space, they can pass `matchExactly: true` as before. We don't strip multiple spaces then.
3. If the consumer wants to highlight individual words **and** however many spaces, then they can pass a regexp directly in the query. Something like `/(\w+)|\s{2,}/` - which will highlight all words and at least two consecutive spaces.

I'm not sure if this is a breaking change. If anything, it was a bug before.
