### ISSUE TITLE
Option to ignore diacritics

### ISSUE THREAD

**Issue by Fabb111** [tricinel/highlight-words#26]
Hello, I use the library for a search field and the matching algorithm ignores diacritics (for example apple matches ápplè), but the highlighting generated from this library does not produce a match. An option to ignore diacritics when generating the chunks would be nice, since the input cannot just be stripped as the outputted chunks of course will be stripped as well.

**Comment by tricinel** [comment]
Hi @Fabb111, just so I understand this correctly...Your code is something like:

```js
const chunks = highlightWords({
  text: 'The word is ápplè not apple',
  query: 'apple'
});
```

And you want the algorithm to match `ápplè` to `apple`? I don't think that's correct as they're different words. But you could write a regex if you wanted to:

```js
const chunks = highlightWords({
  text: 'The word is ápplè not apple',
query: '/(ápplè|apple)/'
});
```

which would give you both results.

Does that help?
