### ISSUE TITLE
Diacretic into regex remove chunked result

### ISSUE THREAD

**Issue by GuillaumeUnice** [tricinel/highlight-words#41]
Hi, I notice a stange behaviour here is my code the Unit Test that fail:

test:
```
highlightWords({
          text: 'Gare Routière, Châteaubriant',
          query: '/[CcÇç]h[AaÀàÁáÂâÃãÄäåĂă]t[EeÈèÉéÊêËë][AaÀàÁáÂâÃãÄäåĂă][UuÙùÚúÛûÜü]br[IiÌìÍíÎîÏï]/i',
          matchExactly: false,
        });
```

and here is the result:
```
[
{key: '6njnsfv4la4', text: 'Gare Routière, ', match: false},
{key: '0aultxkb865', text: 'ant', match: false}
]
```

whereas the expected result should be:
```
[
{key: '6njnsfv4la4', text: 'Gare Routière, ', match: false},
{key: 'dzdzdzd', text: 'Châteaubri', match: true},
{key: '0aultxkb865', text: 'ant', match: false}
]
```

Do I misunderstand something why the matching chunk is omitted?
Thanks in advance

**Comment by tricinel** [comment]
@GuillaumeUnice the regexp is not quite right.

Try this:

```js
query: '/([CcÇç]h[AaÀàÁáÂâÃãÄäåĂă]t[EeÈèÉéÊêËë][AaÀàÁáÂâÃãÄäåĂă][UuÙùÚúÛûÜü]br[IiÌìÍíÎîÏï])/',
```

Notice the capture group (as per the [docs](https://github.com/tricinel/highlight-words?tab=readme-ov-file#usage)).

**Comment by GuillaumeUnice** [comment]
Yes you are perfectly right it's working!

Thanks!
