### ISSUE TITLE
Investigate potential performance issues

### ISSUE THREAD

**Issue by tricinel** [tricinel/highlight-words#7]
If we have a lot of content to parse, we might incur a performance penalty.

Questions to answer:

1. Is there a break point after which we start to notice any performance issues with the splitter?
2. Are there performance issues in the browser only, i.e. when construing the CSSOM or during paint?

Relates to #6

**Comment by gajus** [comment]
Related to this, is uid the most efficient way of assigning unique keys?

**Comment by gajus** [comment]
FYI I've made Liqe compatible with highlight-words

https://github.com/gajus/liqe#highlighting-matches

Would be nice if we could optimize `buildRegexp` implementation to avoid re-parsing regex that Liqe provides. I can adjust regex on Liqe end if needed.

**Comment by tricinel** [comment]
Yup, thinking of different ways to generate those IDs. I have the baseline now, so at least I can see where it makes sense to improve, if at all.

Regarding Liqe, I see they both do searching, with yours being obviously more comprehensive, while highlight-words just does straight-up matches (no comparisons, etc). I fear it may be a big change to make the two work together seamlessly with searching just on one side.
