### ISSUE TITLE
New Option: `clipByLength`

### ISSUE THREAD

**Issue by karlhorky** [tricinel/highlight-words#8]
Ah I was just thinking more about my use case (more info here: https://github.com/tricinel/highlight-words/issues/6), and I was thinking maybe it would help to have an option `clipByLength` in addition to `clipBy`, which would clip with an ellipsis not by number of words but by number of characters?

**Alternative:** keep `clipBy` for the actual **number value**, and add an option `clipByType` with possible values of `"words"` and `"characters"` (defaults to `"words"`)

**Motivation:** With only the `clipBy` option, users may run into problems with super long "words" such as URLs that don't get clipped reasonably.

## Example

```js
const text = 'My dog is a very good boy and is always eating his lunch.';
const chunks = highlightWords({
  text,
  query: 'is',
  clipByLength: 7
});
```

Value for `chunks`:

```js
[
  {
    "text": "My dog ",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " a very ... oy and ",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " always ... ating h",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " lunch.",
    "match": false
  }
]
```

**Comment by tricinel** [comment]
Hey @karlhorky,

To make this clear, let's use an example.

```js
const text = 'My dog is a very good boy and is always eating his lunch.';
const chunks = highlightWords({
  text,
  query: 'is',
  clipBy: 3
});
```
By default, you'd get chunks like:

```js
[
  {
    "text": "... My dog ",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " a very ... boy and ",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " always eating h",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " lunch",
    "match": false
  }
]
```

And this will clip whole words. If you introduce a new option to clip by characters, then you'll get something like:

```js
[
  {
    "text": "... My ",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " a ve ...",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": "... g h",
    "match": false
  },
  {
    "text": "is",
    "match": true
  },
  {
    "text": " lu ...",
    "match": false
  }
]
```
Just want to be sure I got this right and I will investigate the implications.

**Comment by karlhorky** [comment]
Ah, not quite - it would count the 3 characters from the edge closest to the match, just like your algorithm counts the number of words from the matching edge.

I've added an example to the original description above, with 5 characters instead of 3.

**Comment by tricinel** [comment]
Alright, cool, got it. Will investigate 👍 Thanks!

**Comment by karlhorky** [comment]
@tricinel any news on this?

**Comment by tricinel** [comment]
Nothing, no. I doubt this will make it in to be honest, as I see less use cases for having cut-up characters rather than words. Also from an accessibility stand point, I can imagine a screen reader just reciting letters and it pains me 😢
